### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by easella** [Monstars-dev/Goblin#2]
says "404 not found"
![image](https://user-images.githubusercontent.com/74786054/115797336-b237de00-a3a1-11eb-8fc4-33196235df91.png)

**Comment by Pers0n-dev** [comment]
![image](https://user-images.githubusercontent.com/81875430/115890508-daf3be00-a409-11eb-89b7-a9d8fed8c1d3.png)

**Comment by Pers0n-dev** [comment]
i started this 3 days ago lol
